---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages('tidyverse')
install.packages('sf')
install.packages('dplyr')
```
Load the libraries
```{r}
library(tidyverse)
library(sf)
library(dplyr)
```
Load the data
```{r}
yellow_df <- read_csv('../data/yellow_tripdata_2019-01.csv')
green_df <- read_csv('../data/green_tripdata_2019-01.csv')
map_nyc <- read_sf('../data/taxi_zones.shp')
```
Edit the january DF keeping only the column needed for the map.
```{r}
yellow_df_sample <- january_df[sample(nrow(january_df), 753625), ] %>% 
  subset(select = c(tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID, passenger_count))
  
map_nyc$PULocationID <- map_nyc$LocationID
map_nyc$DOLocationID <- map_nyc$LocationID

yellow_PUL <- left_join(yellow_df_sample,map_nyc,"PULocationID")
yellow_nyc_PUL <- subset(yellow_PUL, select = c(tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,Shape_Leng,zone,borough, geometry))

yellow_DOL <- left_join(yellow_df_sample,map_nyc,"DOLocationID")
yellow_nyc_DOL <- subset(yellow_DOL, select = c(tpep_pickup_datetime,tpep_dropoff_datetime,DOLocationID,Shape_Leng,zone,borough, geometry))
```
Plot the NYC map
```{r}
ggplot()+
  geom_sf(
    data = map_nyc
    ) +
  xlab("Longitude") + ylab("Latitude")+
  ggtitle("NYC map")
```

```{r}

```

